/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PublicIndexRouteImport } from './routes/_public.index'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminDeliveryRouteImport } from './routes/admin.delivery'
import { Route as AdminCouponsRouteImport } from './routes/admin.coupons'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminBlogRouteImport } from './routes/admin.blog'
import { Route as AdminBlockedDatesRouteImport } from './routes/admin.blocked-dates'
import { Route as AdminAttributesRouteImport } from './routes/admin.attributes'
import { Route as PublicTermosECondicoesRouteImport } from './routes/_public.termos-e-condicoes'
import { Route as PublicPoliticaDeReembolsoRouteImport } from './routes/_public.politica-de-reembolso'
import { Route as PublicPoliticaDePrivacidadeRouteImport } from './routes/_public.politica-de-privacidade'
import { Route as PublicMinhasEncomendasRouteImport } from './routes/_public.minhas-encomendas'
import { Route as PublicMenuRouteImport } from './routes/_public.menu'
import { Route as PublicEncomendaEventoRouteImport } from './routes/_public.encomenda-evento'
import { Route as PublicCheckoutRouteImport } from './routes/_public.checkout'
import { Route as PublicBlogRouteImport } from './routes/_public.blog'
import { Route as AdminProductsIndexRouteImport } from './routes/admin.products.index'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as PublicBlogIndexRouteImport } from './routes/_public.blog.index'
import { Route as AdminProductsNewRouteImport } from './routes/admin.products.new'
import { Route as AdminProductsIdRouteImport } from './routes/admin.products.$id'
import { Route as AdminOrdersNewRouteImport } from './routes/admin.orders.new'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as PublicProdutoSlugRouteImport } from './routes/_public.produto.$slug'
import { Route as PublicPagarReferenceRouteImport } from './routes/_public.pagar.$reference'
import { Route as PublicEncomendaReferenceRouteImport } from './routes/_public.encomenda.$reference'
import { Route as PublicBlogSlugRouteImport } from './routes/_public.blog.$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDeliveryRoute = AdminDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlogRoute = AdminBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBlockedDatesRoute = AdminBlockedDatesRouteImport.update({
  id: '/blocked-dates',
  path: '/blocked-dates',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAttributesRoute = AdminAttributesRouteImport.update({
  id: '/attributes',
  path: '/attributes',
  getParentRoute: () => AdminRoute,
} as any)
const PublicTermosECondicoesRoute = PublicTermosECondicoesRouteImport.update({
  id: '/termos-e-condicoes',
  path: '/termos-e-condicoes',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPoliticaDeReembolsoRoute =
  PublicPoliticaDeReembolsoRouteImport.update({
    id: '/politica-de-reembolso',
    path: '/politica-de-reembolso',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicPoliticaDePrivacidadeRoute =
  PublicPoliticaDePrivacidadeRouteImport.update({
    id: '/politica-de-privacidade',
    path: '/politica-de-privacidade',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicMinhasEncomendasRoute = PublicMinhasEncomendasRouteImport.update({
  id: '/minhas-encomendas',
  path: '/minhas-encomendas',
  getParentRoute: () => PublicRoute,
} as any)
const PublicMenuRoute = PublicMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEncomendaEventoRoute = PublicEncomendaEventoRouteImport.update({
  id: '/encomenda-evento',
  path: '/encomenda-evento',
  getParentRoute: () => PublicRoute,
} as any)
const PublicCheckoutRoute = PublicCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => PublicRoute,
} as any)
const PublicBlogRoute = PublicBlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => PublicRoute,
} as any)
const AdminProductsIndexRoute = AdminProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const PublicBlogIndexRoute = PublicBlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicBlogRoute,
} as any)
const AdminProductsNewRoute = AdminProductsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminProductsIdRoute = AdminProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProductsRoute,
} as any)
const AdminOrdersNewRoute = AdminOrdersNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const PublicProdutoSlugRoute = PublicProdutoSlugRouteImport.update({
  id: '/produto/$slug',
  path: '/produto/$slug',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPagarReferenceRoute = PublicPagarReferenceRouteImport.update({
  id: '/pagar/$reference',
  path: '/pagar/$reference',
  getParentRoute: () => PublicRoute,
} as any)
const PublicEncomendaReferenceRoute =
  PublicEncomendaReferenceRouteImport.update({
    id: '/encomenda/$reference',
    path: '/encomenda/$reference',
    getParentRoute: () => PublicRoute,
  } as any)
const PublicBlogSlugRoute = PublicBlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => PublicBlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof PublicBlogRouteWithChildren
  '/checkout': typeof PublicCheckoutRoute
  '/encomenda-evento': typeof PublicEncomendaEventoRoute
  '/menu': typeof PublicMenuRoute
  '/minhas-encomendas': typeof PublicMinhasEncomendasRoute
  '/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PublicPoliticaDeReembolsoRoute
  '/termos-e-condicoes': typeof PublicTermosECondicoesRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/blocked-dates': typeof AdminBlockedDatesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/encomenda/$reference': typeof PublicEncomendaReferenceRoute
  '/pagar/$reference': typeof PublicPagarReferenceRoute
  '/produto/$slug': typeof PublicProdutoSlugRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/blog/': typeof PublicBlogIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof PublicCheckoutRoute
  '/encomenda-evento': typeof PublicEncomendaEventoRoute
  '/menu': typeof PublicMenuRoute
  '/minhas-encomendas': typeof PublicMinhasEncomendasRoute
  '/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/politica-de-reembolso': typeof PublicPoliticaDeReembolsoRoute
  '/termos-e-condicoes': typeof PublicTermosECondicoesRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/blocked-dates': typeof AdminBlockedDatesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/': typeof PublicIndexRoute
  '/admin': typeof AdminIndexRoute
  '/blog/$slug': typeof PublicBlogSlugRoute
  '/encomenda/$reference': typeof PublicEncomendaReferenceRoute
  '/pagar/$reference': typeof PublicPagarReferenceRoute
  '/produto/$slug': typeof PublicProdutoSlugRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/blog': typeof PublicBlogIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/products': typeof AdminProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_public/blog': typeof PublicBlogRouteWithChildren
  '/_public/checkout': typeof PublicCheckoutRoute
  '/_public/encomenda-evento': typeof PublicEncomendaEventoRoute
  '/_public/menu': typeof PublicMenuRoute
  '/_public/minhas-encomendas': typeof PublicMinhasEncomendasRoute
  '/_public/politica-de-privacidade': typeof PublicPoliticaDePrivacidadeRoute
  '/_public/politica-de-reembolso': typeof PublicPoliticaDeReembolsoRoute
  '/_public/termos-e-condicoes': typeof PublicTermosECondicoesRoute
  '/admin/attributes': typeof AdminAttributesRoute
  '/admin/blocked-dates': typeof AdminBlockedDatesRoute
  '/admin/blog': typeof AdminBlogRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/delivery': typeof AdminDeliveryRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/pages': typeof AdminPagesRoute
  '/admin/products': typeof AdminProductsRouteWithChildren
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/_public/': typeof PublicIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_public/blog/$slug': typeof PublicBlogSlugRoute
  '/_public/encomenda/$reference': typeof PublicEncomendaReferenceRoute
  '/_public/pagar/$reference': typeof PublicPagarReferenceRoute
  '/_public/produto/$slug': typeof PublicProdutoSlugRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/new': typeof AdminOrdersNewRoute
  '/admin/products/$id': typeof AdminProductsIdRoute
  '/admin/products/new': typeof AdminProductsNewRoute
  '/_public/blog/': typeof PublicBlogIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/products/': typeof AdminProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/checkout'
    | '/encomenda-evento'
    | '/menu'
    | '/minhas-encomendas'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/termos-e-condicoes'
    | '/admin/attributes'
    | '/admin/blocked-dates'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/admin/'
    | '/blog/$slug'
    | '/encomenda/$reference'
    | '/pagar/$reference'
    | '/produto/$slug'
    | '/admin/orders/$id'
    | '/admin/orders/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/blog/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/encomenda-evento'
    | '/menu'
    | '/minhas-encomendas'
    | '/politica-de-privacidade'
    | '/politica-de-reembolso'
    | '/termos-e-condicoes'
    | '/admin/attributes'
    | '/admin/blocked-dates'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/pages'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/'
    | '/admin'
    | '/blog/$slug'
    | '/encomenda/$reference'
    | '/pagar/$reference'
    | '/produto/$slug'
    | '/admin/orders/$id'
    | '/admin/orders/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/blog'
    | '/admin/orders'
    | '/admin/products'
  id:
    | '__root__'
    | '/_public'
    | '/admin'
    | '/_public/blog'
    | '/_public/checkout'
    | '/_public/encomenda-evento'
    | '/_public/menu'
    | '/_public/minhas-encomendas'
    | '/_public/politica-de-privacidade'
    | '/_public/politica-de-reembolso'
    | '/_public/termos-e-condicoes'
    | '/admin/attributes'
    | '/admin/blocked-dates'
    | '/admin/blog'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/delivery'
    | '/admin/faqs'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/pages'
    | '/admin/products'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/settings'
    | '/admin/testimonials'
    | '/_public/'
    | '/admin/'
    | '/_public/blog/$slug'
    | '/_public/encomenda/$reference'
    | '/_public/pagar/$reference'
    | '/_public/produto/$slug'
    | '/admin/orders/$id'
    | '/admin/orders/new'
    | '/admin/products/$id'
    | '/admin/products/new'
    | '/_public/blog/'
    | '/admin/orders/'
    | '/admin/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/delivery': {
      id: '/admin/delivery'
      path: '/delivery'
      fullPath: '/admin/delivery'
      preLoaderRoute: typeof AdminDeliveryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blog': {
      id: '/admin/blog'
      path: '/blog'
      fullPath: '/admin/blog'
      preLoaderRoute: typeof AdminBlogRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/blocked-dates': {
      id: '/admin/blocked-dates'
      path: '/blocked-dates'
      fullPath: '/admin/blocked-dates'
      preLoaderRoute: typeof AdminBlockedDatesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/attributes': {
      id: '/admin/attributes'
      path: '/attributes'
      fullPath: '/admin/attributes'
      preLoaderRoute: typeof AdminAttributesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_public/termos-e-condicoes': {
      id: '/_public/termos-e-condicoes'
      path: '/termos-e-condicoes'
      fullPath: '/termos-e-condicoes'
      preLoaderRoute: typeof PublicTermosECondicoesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/politica-de-reembolso': {
      id: '/_public/politica-de-reembolso'
      path: '/politica-de-reembolso'
      fullPath: '/politica-de-reembolso'
      preLoaderRoute: typeof PublicPoliticaDeReembolsoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/politica-de-privacidade': {
      id: '/_public/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PublicPoliticaDePrivacidadeRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/minhas-encomendas': {
      id: '/_public/minhas-encomendas'
      path: '/minhas-encomendas'
      fullPath: '/minhas-encomendas'
      preLoaderRoute: typeof PublicMinhasEncomendasRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/menu': {
      id: '/_public/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof PublicMenuRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/encomenda-evento': {
      id: '/_public/encomenda-evento'
      path: '/encomenda-evento'
      fullPath: '/encomenda-evento'
      preLoaderRoute: typeof PublicEncomendaEventoRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/checkout': {
      id: '/_public/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof PublicCheckoutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog': {
      id: '/_public/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof PublicBlogRouteImport
      parentRoute: typeof PublicRoute
    }
    '/admin/products/': {
      id: '/admin/products/'
      path: '/'
      fullPath: '/admin/products/'
      preLoaderRoute: typeof AdminProductsIndexRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/_public/blog/': {
      id: '/_public/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof PublicBlogIndexRouteImport
      parentRoute: typeof PublicBlogRoute
    }
    '/admin/products/new': {
      id: '/admin/products/new'
      path: '/new'
      fullPath: '/admin/products/new'
      preLoaderRoute: typeof AdminProductsNewRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/products/$id': {
      id: '/admin/products/$id'
      path: '/$id'
      fullPath: '/admin/products/$id'
      preLoaderRoute: typeof AdminProductsIdRouteImport
      parentRoute: typeof AdminProductsRoute
    }
    '/admin/orders/new': {
      id: '/admin/orders/new'
      path: '/new'
      fullPath: '/admin/orders/new'
      preLoaderRoute: typeof AdminOrdersNewRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/_public/produto/$slug': {
      id: '/_public/produto/$slug'
      path: '/produto/$slug'
      fullPath: '/produto/$slug'
      preLoaderRoute: typeof PublicProdutoSlugRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/pagar/$reference': {
      id: '/_public/pagar/$reference'
      path: '/pagar/$reference'
      fullPath: '/pagar/$reference'
      preLoaderRoute: typeof PublicPagarReferenceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/encomenda/$reference': {
      id: '/_public/encomenda/$reference'
      path: '/encomenda/$reference'
      fullPath: '/encomenda/$reference'
      preLoaderRoute: typeof PublicEncomendaReferenceRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/blog/$slug': {
      id: '/_public/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof PublicBlogSlugRouteImport
      parentRoute: typeof PublicBlogRoute
    }
  }
}

interface PublicBlogRouteChildren {
  PublicBlogSlugRoute: typeof PublicBlogSlugRoute
  PublicBlogIndexRoute: typeof PublicBlogIndexRoute
}

const PublicBlogRouteChildren: PublicBlogRouteChildren = {
  PublicBlogSlugRoute: PublicBlogSlugRoute,
  PublicBlogIndexRoute: PublicBlogIndexRoute,
}

const PublicBlogRouteWithChildren = PublicBlogRoute._addFileChildren(
  PublicBlogRouteChildren,
)

interface PublicRouteChildren {
  PublicBlogRoute: typeof PublicBlogRouteWithChildren
  PublicCheckoutRoute: typeof PublicCheckoutRoute
  PublicEncomendaEventoRoute: typeof PublicEncomendaEventoRoute
  PublicMenuRoute: typeof PublicMenuRoute
  PublicMinhasEncomendasRoute: typeof PublicMinhasEncomendasRoute
  PublicPoliticaDePrivacidadeRoute: typeof PublicPoliticaDePrivacidadeRoute
  PublicPoliticaDeReembolsoRoute: typeof PublicPoliticaDeReembolsoRoute
  PublicTermosECondicoesRoute: typeof PublicTermosECondicoesRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicEncomendaReferenceRoute: typeof PublicEncomendaReferenceRoute
  PublicPagarReferenceRoute: typeof PublicPagarReferenceRoute
  PublicProdutoSlugRoute: typeof PublicProdutoSlugRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicBlogRoute: PublicBlogRouteWithChildren,
  PublicCheckoutRoute: PublicCheckoutRoute,
  PublicEncomendaEventoRoute: PublicEncomendaEventoRoute,
  PublicMenuRoute: PublicMenuRoute,
  PublicMinhasEncomendasRoute: PublicMinhasEncomendasRoute,
  PublicPoliticaDePrivacidadeRoute: PublicPoliticaDePrivacidadeRoute,
  PublicPoliticaDeReembolsoRoute: PublicPoliticaDeReembolsoRoute,
  PublicTermosECondicoesRoute: PublicTermosECondicoesRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicEncomendaReferenceRoute: PublicEncomendaReferenceRoute,
  PublicPagarReferenceRoute: PublicPagarReferenceRoute,
  PublicProdutoSlugRoute: PublicProdutoSlugRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersNewRoute: typeof AdminOrdersNewRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersNewRoute: AdminOrdersNewRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminProductsRouteChildren {
  AdminProductsIdRoute: typeof AdminProductsIdRoute
  AdminProductsNewRoute: typeof AdminProductsNewRoute
  AdminProductsIndexRoute: typeof AdminProductsIndexRoute
}

const AdminProductsRouteChildren: AdminProductsRouteChildren = {
  AdminProductsIdRoute: AdminProductsIdRoute,
  AdminProductsNewRoute: AdminProductsNewRoute,
  AdminProductsIndexRoute: AdminProductsIndexRoute,
}

const AdminProductsRouteWithChildren = AdminProductsRoute._addFileChildren(
  AdminProductsRouteChildren,
)

interface AdminRouteChildren {
  AdminAttributesRoute: typeof AdminAttributesRoute
  AdminBlockedDatesRoute: typeof AdminBlockedDatesRoute
  AdminBlogRoute: typeof AdminBlogRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminDeliveryRoute: typeof AdminDeliveryRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPagesRoute: typeof AdminPagesRoute
  AdminProductsRoute: typeof AdminProductsRouteWithChildren
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAttributesRoute: AdminAttributesRoute,
  AdminBlockedDatesRoute: AdminBlockedDatesRoute,
  AdminBlogRoute: AdminBlogRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminDeliveryRoute: AdminDeliveryRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPagesRoute: AdminPagesRoute,
  AdminProductsRoute: AdminProductsRouteWithChildren,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
